version: '3'
services:
  user-service:
    image: springcloud-user-service
    container_name: user-service
    ports:
      - "8081:8081"
    restart: always
    networks:
      - network-smc

networks:
  network-smc:
    external: true