version: '3'
services:
  user-service:
    image: springcloud-auth2-service
    container_name: springcloud-auth2-service
    ports:
      - "8084:8084"
    restart: always
    networks:
      - network-smc

networks:
  network-smc:
    external: true