version: '3'
services:
  user-service:
    image: springcloud-eureka-service
    container_name: springcloud-eureka-service
    ports:
      - "8087:8087"
    restart: always
    networks:
      - network-smc

networks:
  network-smc:
    external: true