version: '3'
services:
  user-service:
    image: common
    container_name: common
    ports:
      - "8083:8083"
    restart: always
    networks:
      - network-smc

networks:
  network-smc:
    external: true